apiVersion: v2
name: recipe-receiver
description: A Helm chart to deploy the recipe receiver app.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: functio"
    version: "15" 
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo'