name: build_and_push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        - name: Generate build ID
          id: prep
          run: |
             sha=${GITHUB_SHA::8}
             ts=$(date +%s)
             echo "BUILD_ID=${sha}-${ts}" >> $GITHUB_OUTPUT
             
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-jenkins-integration:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-jenkins-integration:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
          if: startsWith(github.ref, 'refs/pull')

        - run: |
           docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-jenkins-integration:prod-${{ steps.prep.outputs.BUILD_ID }}
           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/github-jenkins-integration:prod-${{ steps.prep.outputs.BUILD_ID }}
          if: github.ref == 'refs/heads/master'