name: build_and_push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: Generate build ID
          id: prep
          run: |
             sha=${GITHUB_SHA::8}
             ts=$(date +%s)
             echo "BUILD_ID=${sha}-${ts}" >> $GITHUB_OUTPUT

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins-webhook-relay:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins-webhook-relay:pr-${{github.event.number}}-${{ steps.prep.outputs.BUILD_ID }}
          if: startsWith(github.ref, 'refs/pull')

        - run: |
           docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins-webhook-relay:prod-${{ steps.prep.outputs.BUILD_ID }}
           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/jenkins-webhook-relay:prod-${{ steps.prep.outputs.BUILD_ID }}
          if: github.ref == 'refs/heads/master'
